### ISSUE TITLE
Can't login to demo

### ISSUE THREAD

**Issue by brunomperes** [azexo/Azexo-Composer-WYSIWYG#5]
I could login to the Wordpress, but not on the link given on the Readme file (http://azexo.com/azexo_composer/). I tried to close the dialog, enter "demo" or any other random password, but the dialog keeps reopening.

How can I try the demo? Why is a password needed?

Thanks!

**Comment by azexo** [comment]
Maybe this issue is fixed already. I make few updates in demo. Password is "demo".

Actually this demo not exactly for only JS library - it is demo for Site Builder product to create generators like this http://designmodo.com/generator/

So password need for small protection of design used in AC.

**Comment by azexo** [comment]
Can you check it again ?

**Comment by kuzmany** [comment]
Doesn't work if you press enter. Try click on submit button.

**Comment by brunomperes** [comment]
@kuzmany is right, it doesn't work if press enter, clicking on "Save changes" it works.

**Comment by azexo** [comment]
fixed
